name: urc_ground_station
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - flask
  - pandas
  - matplotlib
  - pyserial
  - opencv
  - pillow
  - pyyaml
  - pip
  - pip:
      - pygame      # Required for F310 Controller
      - PySide6
      - pymavlink
      - pyjoystick
      - inputs